image: rocker/tidyverse

stages:
    - build
    - test

building:
    stage: build
    script:
        - R -e "remotes::install_deps(dependencies = TRUE)"
        - R -e 'devtools::check()'

testing:
    stage: test
    allow_failure: true
    when: on_success
    script:
        - R -e "remotes::install_deps(dependencies = TRUE)"
        - Rscript -e 'install.packages("DT")'
        - Rscript -e 'covr::codecov(quiet = FALSE)'
