image: rocker/verse

stages:
  - document
  - check
  - test
  - deploy

before_script:
  - apt-get update
  - r -e 'install.packages(c("devtools", "roxygen2", "testthat", "covr", "R6", "plotly"))'
  - r -e 'devtools::install_deps()'

documentation:
  stage: document
  script:
    - r -e 'devtools::document()'

check:
  stage: check
  script:
    - r -e 'devtools::check()'

unittests:
  stage: test
  script:
    - r -e 'devtools::test()'

codecov:
  stage: test
  script:
    - r -e 'covr::codecov()'

install:
  stage: deploy
  script:
    - r -e 'devtools::install()'
