image: rocker/verse

stages:
  - TestPackage

before_script:
  - apt-get update
  - r -e 'install.packages(c("devtools", "roxygen2", "testthat", "covr", "R6", "plotly"))'
  - r -e 'devtools::install_deps()'

documentation:
  stage: TestPackage
  script:
    - Rscript tools/Check_documentation.R

check:
  stage: TestPackage
  script:
    - r -e 'devtools::build()'
    - cd ..
    - R CMD check --as-cran breedSimulatR_*.tar.gz

unittests:
  stage: TestPackage
  script:
    - r -e 'devtools::test()'

codecov:
  stage: TestPackage
  script:
    - r -e 'covr::codecov()'

install:
  stage: TestPackage
  script:
    - r -e 'devtools::install()'
